# Generated by Django 4.2.13 on 2024-06-17 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=100)),
                ('fecha_de_solicitud', models.DateField()),
                ('estatus', models.CharField(max_length=100)),
                ('dias_solicitados', models.IntegerField()),
            ],
            options={
                'db_table': 'registro_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.CharField(max_length=100)),
                ('numero_empleado', models.IntegerField()),
                ('fecha_de_entrada', models.DateField()),
                ('fecha_de_corte', models.DateField(default=datetime.date.today)),
                ('dias_utilizados', models.IntegerField(default=0)),
                ('ultima_fecha_de_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'vacaciones',
            },
        ),
    ]
