# Generated by Django 4.2.13 on 2024-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golpes_diarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramental', models.CharField(max_length=30)),
                ('terminal', models.CharField(max_length=30)),
                ('fecha_reg', models.CharField(max_length=30)),
                ('golpesDiarios', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'mant_golpes',
            },
        ),
        migrations.CreateModel(
            name='Herramental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramental', models.CharField(max_length=30)),
                ('terminal', models.CharField(max_length=30)),
                ('fecha_reg', models.CharField(max_length=30)),
                ('golpesDiarios', models.IntegerField(default=0)),
                ('golpesTotales', models.IntegerField(default=0)),
                ('maquina', models.CharField(max_length=80)),
                ('totalmant', models.IntegerField(default=0)),
                ('mantenimiento', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'mant_golpes_diarios',
            },
        ),
        migrations.CreateModel(
            name='new_mant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.CharField(max_length=30)),
                ('tiempos', models.CharField(max_length=30)),
                ('herramental', models.CharField(max_length=30)),
                ('terminal', models.CharField(max_length=30)),
                ('Minutos', models.IntegerField(default=0)),
                ('quien', models.CharField(max_length=80)),
                ('docMant', models.CharField(max_length=800)),
            ],
            options={
                'db_table': 'mant_herramental',
            },
        ),
        migrations.CreateModel(
            name='Paros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30)),
                ('equipo', models.CharField(max_length=80)),
                ('nombreEquipo', models.CharField(max_length=80)),
                ('dano', models.CharField(max_length=80)),
                ('quien', models.CharField(max_length=80)),
                ('area', models.CharField(max_length=80)),
                ('atiende', models.CharField(max_length=80)),
                ('trabajo', models.CharField(max_length=80)),
                ('Tiempo', models.CharField(max_length=80)),
                ('inimant', models.CharField(max_length=80)),
                ('finhora', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'registro_paro',
            },
        ),
    ]
