# Generated by Django 4.2.13 on 2024-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAlmacen',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('fecha_registro', models.CharField(max_length=30)),
                ('mnfint', models.CharField(max_length=30)),
                ('mnfext', models.CharField(max_length=30)),
                ('cantidad', models.FloatField()),
                ('impoNum', models.CharField(max_length=30)),
                ('impoFecha', models.CharField(max_length=30)),
                ('codigoUnico', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'control_almacen',
            },
        ),
    ]
