# Generated by Django 4.2.13 on 2024-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('calibre', models.IntegerField(default=0, max_length=2)),
                ('cliente', models.CharField(max_length=80)),
                ('Num_part', models.CharField(max_length=50)),
                ('wo', models.CharField(max_length=6)),
                ('presion', models.FloatField(default=0.0)),
                ('forma', models.CharField(max_length=80)),
                ('cont', models.CharField(max_length=80)),
                ('quien', models.CharField(max_length=80)),
                ('val', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'pulltest',
            },
        ),
    ]
