# Generated by Django 4.2.13 on 2024-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulltest',
            name='calibre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pulltest',
            name='tipo',
            field=models.CharField(default=' ', max_length=4),
        ),
    ]
