# Generated by Django 4.2.13 on 2024-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullTest', '0003_alter_pulltest_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulltest',
            old_name='cliente',
            new_name='Cliente',
        ),
        migrations.AlterField(
            model_name='pulltest',
            name='fecha',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='pulltest',
            table='registro_pull',
        ),
    ]
